# Google Sheets

SPREADSHEET_ID = "1GJz57eO5uBvkz7sfrrcK72EvVRzXwZTDCemHPLN053U"

# Células

CELL_VES_BUY = "I8"
CELL_VES_SELL = "J8"

CELL_VES_BUY_METHOD = "I10"
CELL_VES_SELL_METHOD = "J10"

CELL_BRL_BUY = "K8"
CELL_BRL_SELL = "L8"
