name: Atualizar Taxas P2P

on:
  workflow_dispatch:

jobs:
  atualizar:

    runs-on: ubuntu-latest

    steps:

      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Criar credenciais
        run: |
          mkdir -p credentials
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials/service_account.json

      - name: Executar projeto
        run: |
          python main.py
